import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useInView } from "framer-motion";
import { useRef } from "react";
import {
  Upload,
  FileImage,
  CheckCircle,
  AlertTriangle,
  X,
  Sparkles,
  Shield,
  Eye,
  Zap,
  ChevronRight,
} from "lucide-react";
import { Button } from "./ui/button";

type AnalysisResult = {
  authenticityScore: number;
  status: "AUTHENTIC" | "MANIPULATED" | "AI-GENERATED";
  riskLevel: "LOW" | "MEDIUM" | "HIGH";
  anomalies: { title: string; description: string; severity: "low" | "medium" | "high" }[];
  realityTrace: string[];
  recommendation: string;
};

const preloadedExamples: Record<string, AnalysisResult> = {
  "fake-upi": {
    authenticityScore: 18,
    status: "MANIPULATED",
    riskLevel: "HIGH",
    anomalies: [
      { title: "Font Mismatch Detected", description: "Transaction ID uses non-standard font rendering", severity: "high" },
      { title: "Template Violation", description: "UPI layout doesn't match official NPCI format", severity: "high" },
      { title: "Compression Artifacts", description: "Inconsistent JPEG compression in amount area", severity: "medium" },
      { title: "Timestamp Anomaly", description: "Time format inconsistent with device region", severity: "low" },
    ],
    realityTrace: ["Screenshot Captured", "Image Editor (Photoshop)", "Text Overlay Added", "JPEG Export", "Shared"],
    recommendation: "Do not accept as payment proof. Verify through original banking app.",
  },
  "fake-whatsapp": {
    authenticityScore: 24,
    status: "MANIPULATED",
    riskLevel: "HIGH",
    anomalies: [
      { title: "Bubble Spacing Error", description: "Message bubble spacing differs by 4px from official app", severity: "high" },
      { title: "Timestamp Format Wrong", description: "Time display format doesn't match WhatsApp standard", severity: "medium" },
      { title: "Font Weight Mismatch", description: "Message text uses incorrect font weight", severity: "medium" },
      { title: "Status Icon Anomaly", description: "Read receipt icon rendered incorrectly", severity: "low" },
    ],
    realityTrace: ["Fake Chat Generator", "Screenshot Tool", "Crop Applied", "PNG Export"],
    recommendation: "This screenshot was likely created using a fake chat generator. Do not trust content.",
  },
  "ai-generated": {
    authenticityScore: 12,
    status: "AI-GENERATED",
    riskLevel: "MEDIUM",
    anomalies: [
      { title: "Diffusion Artifacts Found", description: "Characteristic AI model fingerprints detected", severity: "high" },
      { title: "No EXIF Metadata", description: "Image lacks camera metadata - synthetic origin", severity: "high" },
      { title: "Texture Anomalies", description: "Unnatural texture patterns in background", severity: "medium" },
      { title: "Lighting Inconsistency", description: "Shadow directions don't match light source", severity: "medium" },
    ],
    realityTrace: ["AI Image Generator (Stable Diffusion)", "Upscaling Applied", "JPEG Conversion"],
    recommendation: "This image was generated by AI. Verify claims independently.",
  },
};

const analysisSteps = [
  "Reading file metadata...",
  "Analyzing pixel patterns...",
  "Checking structural consistency...",
  "Running AI detection models...",
  "Cross-referencing templates...",
  "Generating report...",
];

export function DemoSection() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });
  const [isDragging, setIsDragging] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [uploadedFile, setUploadedFile] = useState<string | null>(null);

  const runAnalysis = useCallback((exampleKey?: string) => {
    setIsAnalyzing(true);
    setCurrentStep(0);
    setResult(null);

    const interval = setInterval(() => {
      setCurrentStep((prev) => {
        if (prev >= analysisSteps.length - 1) {
          clearInterval(interval);
          setTimeout(() => {
            setIsAnalyzing(false);
            setResult(
              exampleKey
                ? preloadedExamples[exampleKey]
                : preloadedExamples["fake-upi"]
            );
          }, 500);
          return prev;
        }
        return prev + 1;
      });
    }, 600);
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragging(false);
      const file = e.dataTransfer.files[0];
      if (file) {
        setUploadedFile(file.name);
        runAnalysis();
      }
    },
    [runAnalysis]
  );

  const handleFileSelect = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (file) {
        setUploadedFile(file.name);
        runAnalysis();
      }
    },
    [runAnalysis]
  );

  const handleExampleClick = (key: string) => {
    setUploadedFile(`Example: ${key.replace("-", " ").toUpperCase()}`);
    runAnalysis(key);
  };

  const resetDemo = () => {
    setResult(null);
    setUploadedFile(null);
    setIsAnalyzing(false);
    setCurrentStep(0);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "AUTHENTIC":
        return "text-green-400";
      case "MANIPULATED":
        return "text-destructive";
      case "AI-GENERATED":
        return "text-orange-400";
      default:
        return "text-foreground";
    }
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case "LOW":
        return "text-green-400 bg-green-400/10";
      case "MEDIUM":
        return "text-yellow-400 bg-yellow-400/10";
      case "HIGH":
        return "text-destructive bg-destructive/10";
      default:
        return "text-foreground";
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case "low":
        return "border-green-400/50 bg-green-400/5";
      case "medium":
        return "border-yellow-400/50 bg-yellow-400/5";
      case "high":
        return "border-destructive/50 bg-destructive/5";
      default:
        return "border-border";
    }
  };

  return (
    <section id="demo" className="relative py-24 lg:py-32 overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-b from-background via-navy-light/20 to-background" />
      <div className="absolute top-1/2 right-0 w-[600px] h-[600px] bg-purple/5 rounded-full blur-[150px]" />
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-border to-transparent" />

      <div ref={ref} className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full glass-card mb-6">
            <Eye className="w-4 h-4 text-cyan" />
            <span className="text-sm text-muted-foreground">Live Demo</span>
          </div>
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4">
            See It <span className="text-gradient">In Action</span>
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Upload any image and watch TrustLens reveal the truth
          </p>
        </motion.div>

        {/* Demo Interface */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="glass-card rounded-3xl p-4 md:p-8 shadow-card"
        >
          <div className="grid lg:grid-cols-5 gap-6">
            {/* Upload Area */}
            <div className="lg:col-span-2 space-y-4">
              {/* Drag & Drop Zone */}
              <div
                onDragOver={(e) => {
                  e.preventDefault();
                  setIsDragging(true);
                }}
                onDragLeave={() => setIsDragging(false)}
                onDrop={handleDrop}
                className={`relative border-2 border-dashed rounded-2xl p-8 text-center transition-all duration-300 ${
                  isDragging
                    ? "border-cyan bg-cyan/5"
                    : "border-border hover:border-cyan/50"
                }`}
              >
                <input
                  type="file"
                  accept="image/*,.pdf"
                  onChange={handleFileSelect}
                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                />
                <Upload className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
                <p className="font-medium mb-2">Drag & drop or click to upload</p>
                <p className="text-sm text-muted-foreground">
                  JPG, PNG, PDF, MP4 • Max 10MB
                </p>
              </div>

              {/* Example Buttons */}
              <div className="space-y-2">
                <p className="text-sm text-muted-foreground">Or try an example:</p>
                <div className="grid gap-2">
                  {[
                    { key: "fake-upi", label: "Fake UPI Slip" },
                    { key: "fake-whatsapp", label: "Fake WhatsApp Screenshot" },
                    { key: "ai-generated", label: "AI-Generated Image" },
                  ].map((example) => (
                    <Button
                      key={example.key}
                      variant="glass"
                      className="justify-start"
                      onClick={() => handleExampleClick(example.key)}
                      disabled={isAnalyzing}
                    >
                      <FileImage className="w-4 h-4 mr-2" />
                      Try: {example.label}
                    </Button>
                  ))}
                </div>
              </div>

              {/* Current File */}
              {uploadedFile && (
                <div className="glass-card rounded-xl p-4 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <FileImage className="w-5 h-5 text-cyan" />
                    <span className="text-sm truncate max-w-[200px]">{uploadedFile}</span>
                  </div>
                  <button onClick={resetDemo} className="text-muted-foreground hover:text-foreground">
                    <X className="w-4 h-4" />
                  </button>
                </div>
              )}
            </div>

            {/* Results Dashboard */}
            <div className="lg:col-span-3 space-y-4">
              <AnimatePresence mode="wait">
                {/* Analyzing State */}
                {isAnalyzing && (
                  <motion.div
                    key="analyzing"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="glass-card rounded-2xl p-8 text-center"
                  >
                    <div className="relative w-20 h-20 mx-auto mb-6">
                      <div className="absolute inset-0 rounded-full border-4 border-muted" />
                      <div className="absolute inset-0 rounded-full border-4 border-cyan border-t-transparent animate-spin" />
                      <Shield className="absolute inset-0 m-auto w-8 h-8 text-cyan" />
                    </div>
                    <h3 className="text-lg font-semibold mb-4">Analyzing Content...</h3>
                    <div className="space-y-3 max-w-sm mx-auto">
                      {analysisSteps.map((step, index) => (
                        <div
                          key={index}
                          className={`flex items-center gap-3 text-sm transition-all duration-300 ${
                            index <= currentStep
                              ? "text-foreground"
                              : "text-muted-foreground/50"
                          }`}
                        >
                          {index < currentStep ? (
                            <CheckCircle className="w-4 h-4 text-green-400" />
                          ) : index === currentStep ? (
                            <Zap className="w-4 h-4 text-cyan animate-pulse" />
                          ) : (
                            <div className="w-4 h-4 rounded-full border border-muted-foreground/30" />
                          )}
                          {step}
                        </div>
                      ))}
                    </div>
                  </motion.div>
                )}

                {/* Results State */}
                {result && !isAnalyzing && (
                  <motion.div
                    key="results"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0 }}
                    className="space-y-4"
                  >
                    {/* Authenticity Score */}
                    <div className="glass-card rounded-2xl p-6">
                      <div className="flex items-center justify-between mb-4">
                        <h4 className="font-semibold">Authenticity Score</h4>
                        <span className={`text-3xl font-bold ${result.authenticityScore > 70 ? "text-green-400" : result.authenticityScore > 40 ? "text-yellow-400" : "text-destructive"}`}>
                          {result.authenticityScore}%
                        </span>
                      </div>
                      <div className="h-3 rounded-full bg-muted overflow-hidden">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `${result.authenticityScore}%` }}
                          transition={{ duration: 1 }}
                          className={`h-full rounded-full ${result.authenticityScore > 70 ? "bg-gradient-to-r from-green-500 to-emerald-400" : result.authenticityScore > 40 ? "bg-gradient-to-r from-yellow-500 to-orange-400" : "bg-gradient-to-r from-red-500 to-destructive"}`}
                        />
                      </div>
                      <div className="flex items-center justify-between mt-4">
                        <span className={`text-lg font-bold ${getStatusColor(result.status)}`}>
                          {result.status}
                        </span>
                        <span className={`px-3 py-1 rounded-full text-sm font-medium ${getRiskColor(result.riskLevel)}`}>
                          {result.riskLevel} RISK
                        </span>
                      </div>
                    </div>

                    {/* Anomalies */}
                    <div className="glass-card rounded-2xl p-6">
                      <h4 className="font-semibold mb-4 flex items-center gap-2">
                        <AlertTriangle className="w-4 h-4 text-yellow-400" />
                        Anomalies Detected ({result.anomalies.length})
                      </h4>
                      <div className="space-y-3">
                        {result.anomalies.map((anomaly, index) => (
                          <div
                            key={index}
                            className={`border rounded-xl p-3 ${getSeverityColor(anomaly.severity)}`}
                          >
                            <div className="font-medium text-sm">{anomaly.title}</div>
                            <div className="text-xs text-muted-foreground mt-1">
                              {anomaly.description}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Reality Trace */}
                    <div className="glass-card rounded-2xl p-6">
                      <h4 className="font-semibold mb-4 flex items-center gap-2">
                        <Sparkles className="w-4 h-4 text-purple" />
                        Reality Trace™
                      </h4>
                      <div className="flex flex-wrap items-center gap-2">
                        {result.realityTrace.map((step, index) => (
                          <div key={index} className="flex items-center">
                            <span className="px-3 py-1.5 rounded-lg bg-muted text-sm">
                              {step}
                            </span>
                            {index < result.realityTrace.length - 1 && (
                              <ChevronRight className="w-4 h-4 text-muted-foreground mx-1" />
                            )}
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Recommendation */}
                    <div className="glass-card rounded-2xl p-6 border-l-4 border-cyan">
                      <h4 className="font-semibold mb-2 flex items-center gap-2">
                        <Shield className="w-4 h-4 text-cyan" />
                        Recommendation
                      </h4>
                      <p className="text-muted-foreground text-sm">
                        {result.recommendation}
                      </p>
                    </div>
                  </motion.div>
                )}

                {/* Empty State */}
                {!result && !isAnalyzing && (
                  <motion.div
                    key="empty"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="glass-card rounded-2xl p-12 text-center"
                  >
                    <Shield className="w-16 h-16 mx-auto mb-4 text-muted-foreground/50" />
                    <h3 className="text-lg font-semibold mb-2">Upload to Start Analysis</h3>
                    <p className="text-sm text-muted-foreground">
                      Drag & drop a file or select an example to see TrustLens in action
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
